### ISSUE TITLE
Figure out how to create a GitHub Repo on behalf of a user

### ISSUE THREAD

**Issue by humphd** [humphd/my-photohub#1]
We want to allow someone to login to their GitHub account, and then be able to create a new repo on their behalf.  I'm not 100% sure how to do this.  We can probably use https://github.com/octokit/rest.js/ to work with the GitHub API, but the security aspect of this (i.e., doing this action on the part of another use) is going to take some research and trial and error.

**Comment by SerpentBytes** [comment]
@humphd Can I be assigned this issue for 0.3?

**Comment by humphd** [comment]
Sure, go for it.

**Comment by SerpentBytes** [comment]
@humphd  I am working on this now. Is it okay if we turn this into a React project?

**Comment by humphd** [comment]
Sure, sounds good.  NOTE: this part of the problem won't require React.

**Comment by SerpentBytes** [comment]
I did some research, and it seems like the _safest_ way to authenticate users using GitHub API is to set up the project as a GitHub App. Since Octobit is compatible with GitHub apps integration we can  use the webhooks provided by ocktokit/rest.js to create a repo after the end user is authenticated using GitHub Apps as an authentication method. We can also use PAT,  which is the most secure form authentication method aftet Github Apps. If you want me to take another approach, please let me know.

Reference:
https://iamhughes.com/github-api-authentication-methods-best-practices/#t-1667434141730
